"""Default model tier definitions for routing."""

from __future__ import annotations

from .models import ModelTier

DEFAULT_TIERS: list[ModelTier] = [
    ModelTier(
        name="local",
        provider="ollama",
        model="qwen3-coder:30b-a3b-q8_0",
        cost_rank=1,
        complexity_min=0,
        complexity_max=3,
        strengths=["formatting", "simple_edits", "crud"],
    ),
    ModelTier(
        name="gemini-flash-lite",
        provider="google",
        model="gemini-2.5-flash-lite",
        cost_rank=2,
        complexity_min=0,
        complexity_max=4,
        strengths=["bulk_extraction", "classification", "cheap_summarization"],
    ),
    ModelTier(
        name="deepseek-flash",
        provider="deepseek",
        model="deepseek-v4-flash",
        cost_rank=3,
        complexity_min=0,
        complexity_max=5,
        strengths=["boilerplate", "simple_features", "tests", "crud"],
    ),
    ModelTier(
        name="gemini-flash",
        provider="google",
        model="gemini-2.5-flash",
        cost_rank=4,
        complexity_min=1,
        complexity_max=6,
        strengths=["multimodal", "video_analysis", "image_analysis", "brand_assets"],
    ),
    ModelTier(
        name="deepseek-pro",
        provider="deepseek",
        model="deepseek-v4-pro",
        cost_rank=5,
        complexity_min=2,
        complexity_max=8,
        strengths=["code_generation", "debugging", "refactor", "feature"],
    ),
    ModelTier(
        name="kimi",
        provider="moonshot",
        model="kimi-k2.6",
        cost_rank=6,
        complexity_min=3,
        complexity_max=8,
        strengths=["documentation", "agentic_loops", "research"],
    ),
    ModelTier(
        name="grok",
        provider="xai",
        model="grok-4.3",
        cost_rank=7,
        complexity_min=4,
        complexity_max=10,
        strengths=["competitor_intel", "ckg_building", "deep_reasoning",
                   "truthful_insights", "market_analysis"],
    ),
    ModelTier(
        name="gemini-3.5-flash",
        provider="google",
        model="gemini-3.5-flash",
        cost_rank=8,
        complexity_min=3,
        complexity_max=9,
        strengths=["agentic_coding", "tool_use", "mcp", "multimodal",
                   "fast_reasoning"],
    ),
    ModelTier(
        name="gemini-pro-search",
        provider="google",
        model="gemini-3.1-pro",
        cost_rank=9,
        complexity_min=5,
        complexity_max=10,
        strengths=["deep_research", "google_grounding", "competitor_intel",
                   "market_research", "large_context"],
    ),
    ModelTier(
        name="codex",
        provider="openai",
        model="codex",
        cost_rank=10,
        complexity_min=4,
        complexity_max=10,
        strengths=["review", "bulk_generation", "api_design"],
        role="validator",
    ),
    ModelTier(
        name="claude",
        provider="anthropic",
        model="claude-sonnet-4.6",
        cost_rank=11,
        complexity_min=5,
        complexity_max=10,
        strengths=["complex_reasoning", "security", "architecture"],
    ),
    ModelTier(
        name="claude-opus",
        provider="anthropic",
        model="claude-opus-4.7",
        cost_rank=12,
        complexity_min=7,
        complexity_max=10,
        strengths=["quality_critical", "security_audit", "system_design",
                   "complex_debugging"],
    ),
]
